### PR TITLE
fix: EnrichedActivity Not Returning Reactions

### LINKED ISSUE #61: EnrichedActivity Not Returning Reactions
I am not sure what is happening. I add a reaction like so:
```
widget.streamClient.reactions
                      .add('like', widget.post.id,
                          userId: widget.streamClient.currentUser.userId,
                          data: {
                            'value': index,
                          });
```
Then I get the enriched activities like so:
```
 timeline
        .getEnrichedActivities(
            limit: 100,
            offset: 0,
            flags: EnrichmentFlags()
                .withReactionCounts()
                .withOwnReactions()
                .withRecentReactions())
```
It will return the activities but not any reactions it's like they do not get updated even though I get a return value.

```
I/flutter (29491): *** Request ***
I/flutter (29491): uri: https://api.stream-io-api.com/api/v1.0/reaction/?api_key=hmwext26344q&location=unspecified
I/flutter (29491): method: POST
I/flutter (29491): responseType: ResponseType.json
I/flutter (29491): followRedirects: true
I/flutter (29491): connectTimeout: 10000
I/flutter (29491): sendTimeout: 0
I/flutter (29491): receiveTimeout: 10000
I/flutter (29491): receiveDataWhenStatusError: true
I/flutter (29491): extra: {}
I/flutter (29491): headers:
I/flutter (29491):  stream-auth-type: jwt
I/flutter (29491):  x-stream-client: stream-feed-dart-client-android-0.1.2
I/flutter (29491):  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMEFKWmZVT1Rxb1hMOHlCeVhZODZUYzBMS3VsMnBlcnNvbmFsIn0.YnnMv2ApNpKPdh6aBCQm9hlB-W7C0DDyuzAMO2g61IA
I/flutter (29491):  content-type: application/json; charset=utf-8
I/flutter (29491): data:
I/flutter (29491): Reaction(null, like, bc1118f0-b2d2-11eb-8c76-1254437355c5, 0AJZfUOTqoXL8yByXY86Tc0LKul2personal, null, null, null, null, null, null, {value: 4}, null, null)
I/flutter (29491):
I/flutter (29491): *** Response ***
I/flutter (29491): uri: https://api.stream-io-api.com/api/v1.0/reaction/?api_key=hmwext26344q&location=unspecified
I/flutter (29491): statusCode: 201
I/flutter (29491): headers:
I/flutter (29491):  connection: keep-alive
I/flutter (29491):  cache-control: no-cache
I/flutter (29491):  date: Wed, 12 May 2021 19:14:05 GMT
I/flutter (29491):  access-control-allow-origin: *
I/flutter (29491):  x-ratelimit-limit: 1000
I/flutter (29491):  x-ratelimit-reset: 1620846900
I/flutter (29491):  x-ratelimit-remaining: 999
I/flutter (29491):  content-type: application/json;charset=utf-8
I/flutter (29491):  access-control-max-age: 86400
I/flutter (29491):  server: nginx
I/flutter (29491):  access-control-allow-headers: x-requested-with, content-type, accept, origin, authorization, x-csrftoken, x-stream-client, stream-auth-type
I/flutter (29491):  access-control-allow-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
I/flutter (29491):  content-length: 691
I/flutter (29491): Response Text:
I/flutter (29491): {"created_at":"2021-05-12T19:14:05.323360Z","updated_at":"2021-05-12T19:14:05.323360Z","id":"e95a85d0-b44b-4017-9fcd-cfae75d62d90","user_id":"0AJZfUOTqoXL8yByXY86Tc0LKul2personal","user":{"created_at":"2021-04-13T23:04:05.306176Z","updated_at":"2021-04-13T23:04:05.306176Z","id":"0AJZfUOTqoXL8yByXY86Tc0LKul2personal","data":{"gender":"Female","name":"jane doe","photo":"https://firebasestorage.googleapis.com/v0/b/fire-snab.appspot.com/o/profile-image-placeholder.png?alt=media&token=b17598bb-a510-4167-8354-ab75642ba89e"}},"kind":"like","activity_id":"bc1118f0-b2d2-11eb-8c76-1254437355c5","data":{"value":4},"parent":"","latest_children":{},"children_counts":{},"duration":"5.79ms"}
I/flutter (29491):
I/flutter (29491): Reaction(e95a85d0-b44b-4017-9fcd-cfae75d62d90, like, bc1118f0-b2d2-11eb-8c76-1254437355c5, 0AJZfUOTqoXL8yByXY86Tc0LKul2personal, , 2021-05-12 19:14:05.323360Z, 2021-05-12 19:14:05.323360Z, null, {created_at: 2021-04-13T23:04:05.306176Z, updated_at: 2021-04-13T23:04:05.306176Z, id: 0AJZfUOTqoXL8yByXY86Tc0LKul2personal, data: {gender: Female, name: jane doe, photo: https://firebasestorage.googleapis.com/v0/b/fire-snab.appspot.com/o/profile-image-placeholder.png?alt=media&token=b17598bb-a510-4167-8354-ab75642ba89e}}, null, {value: 4}, {}, {})
```

### PR DESCRIPTION
**Pull request by sachaarbonel**
fix #61

### CODE REVIEW

File: packages/stream_feed/test/models_test.dart [hunk 1]
```diff
@@ -113,6 +124,11 @@ void main() {
       });
     });
   });
+
+  test('EnrichedActivity issue 61', () {
+    final enrichedActivity = EnrichedActivity.fromJson(
+        jsonFixture('enriched_activity_issue61.json'));
```
Comment (xsahil03x) [inline packages/stream_feed/test/models_test.dart:130]: maybe also check for null or empty reaction fields

File: packages/stream_feed/test/models_test.dart [hunk 2]
```diff
@@ -113,6 +124,12 @@ void main() {
...
+    expect(enrichedActivity.latestReactions, isNotNull);
+  });
```
Comment (xsahil03x) [inline packages/stream_feed/test/models_test.dart:132]:
```suggestion
  expect(enrichedActivity.ownReactions, isNotNull);
  expect(enrichedActivity.reactionCounts, isNotNull);
  });
```

**Review by xsahil03x — APPROVED** [review]
LGTM
